api_platform:
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  http_cache:
    invalidation:
      enabled: true
      # varnish_urls: ['%env(VARNISH_URL)%'] ## this problem still needs to be fixed
    max_age: 0
    shared_max_age: 3600
    vary: ["Content-Type", "Authorization"]
    public: true
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
  collection:
    order_parameter_name: "_order"
    pagination:
      page_parameter_name: _page
      #client_enabled: true
      #enabled_parameter_name: pagination
      items_per_page: 10
      client_items_per_page: true #disabled by default
      items_per_page_parameter_name: itemsPerPage
      maximum_items_per_page: 20
      partial: false
      client_partial: true
      partial_parameter_name: "partial"
